services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096
    volumes:
      - /opt/jellyfin/cache:/cache
      - /opt/jellyfin/config:/config
      - type: bind
        source: /mnt/jellyfin_media
        target: /media1
        read_only: true
      - type: bind
        source: /mnt/jellyfin_media2
        target: /media2
        read_only: true
    restart: unless-stopped
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.1.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    ports:
      - 9100:9100
    volumes:
    - /:/host:ro,rslave
